[package]
name          = "proptest-arbitrary"
version       = "0.1.0"
authors       = ["Mazdak Farrokhzad <twingoow@gmail.com>"]
license       = "MIT/Apache-2.0"
readme        = "README.md"

repository    = "https://github.com/Centril/proptest-arbitrary"
documentation = "https://docs.rs/proptest-arbitrary"

keywords      = ["arbitrary", "property", "testing", "quickcheck", "hypothesis"]
categories    = ["development-tools::testing"]

description = """
The Arbitrary trait for proptest and implementations for standard types.
"""

[dependencies]
frunk_core = "0.0.21"
    #{ git = "https://github.com/Centril/frunk", branch = "feature/partial-default-and-conversions" }
frunk_derives = "0.0.22"
    #{ git = "https://github.com/Centril/frunk", branch = "feature/partial-default-and-conversions" }

init_with = "1.1.0"
derive_more = "0.7.0"
proptest = "0.3.1"
bit-set  = "0.4.0"